### ISSUE TITLE
ModuleNotFoundError: No module named 'gsplat.pytorch_ssim'

### ISSUE THREAD

**Issue by minmojamoja** [scomup/simple_gaussian_splatting#3]
Now I'm following the data preparation, but I met the problem about the module of the gsplat.
This kind of issue has occurred. I tried downloading Git, but it didn't work.
```
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from gsplat.pytorch_ssim import gau_loss
ModuleNotFoundError: No module named 'gsplat.pytorch_ssim'
```

I will outline what I have attempted below. Of course, I did it in a virtual environment.

pip install git+https://github.com/nerfstudio-project/gsplat.git
pip install git+https://github.com/nerfstudio-project/gsplat.git@v0.1.0
pip install gsplat==0.1.11
pip install gsplat==1.3.0

now status: 
gsplat                            1.3.0
gsplatcu                          0.0.0

**Comment by scomup** [comment]
My project doesn't use https://github.com/nerfstudio-project/gsplat.git. ,which you already installed. 
The `gsplat` is in my repository: https://github.com/scomup/EasyGaussianSplatting/tree/main/gsplat."
Please check the README; you only need to follow these steps:

```bash
pip3 install -r requirements.txt
pip3 install gsplatcu/.
```

**Comment by minmojamoja** [comment]
I uninstalled gsplat and gsplatcu, deleted the gsplatcu folder, re-downloaded it, and ran the code from the README, which solved the issue. Thank you very much.

**Comment by scomup** [comment]
Great!
